version: '3'

services:

  nginx:
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - ./app:/var/www/html
      - ./build/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - backend

  php:
    build: ./build/php
    volumes:
      - ./app:/var/www/html
    networks:
      - backend

networks:
  backend:
    driver: bridge